version: "3.7"

services:
  db:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ./docker/db/data:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}